app.worker.enabled=true
spring.main.web-application-type=none
spring.flyway.enabled=false

app.email.provider=smtp
app.email.from=no-reply@job-scheduler.local
spring.mail.host=localhost
spring.mail.port=1025

spring.cloud.aws.sqs.enabled=true
app.worker.max-receive-count=5

spring.cloud.aws.sqs.queue-not-found-strategy=fail